- .github/workflows/ci.yml
- src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.h
- src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.inl
Using "using namespace" in header is bad, m'kay....
And this component is even not usable by the way 😵 (because of not SOFAEVE)
but the instantiation itself could not even compile as well (use of deprecated/deleted functions)
> Fix ImplicitSurfaceAdaptiveConstraint compilation

- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
Some `AdvancedTimer` stepBegin/stepEnd had spelling inconsistencies
> [src] Fix AdvancedTimer logs

- .github/workflows/ci.yml
- examples/3instruments_collis.scn
Based on 
- #26 
Sofa does not come with the regression executable.
So this PR needs https://github.com/sofa-framework/Regression/pull/32 to be merged and triggered to generate binaries.
Those binaries will used by this action to execute regression checks.
For now it is downloading binaries from my fork but it needs to be updated.
macOS has some problem with rpath and stuff, and I am lazy to find out the cause for now 🥸
> Execute regression test(s) for BeamAdapter scenes on Github Actions

- src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.cpp
- src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.h
- src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.inl
Always going under the radar because it needs SofaImplicitField...
\+ some cleanup
> Compile ImplicitSurfaceAdaptiveConstraint with nocompat

- BeamAdapter_test/BeamInterpolation_test.cpp
- BeamAdapter_test/component/forcefield/AdaptiveBeamForceFieldAndMassTest.cpp
Add other tests on:
- component creation
- check default Data values
- check position at init and after n simulation step on a simple beam pendulum
> [Tests] Add more tests for AdaptiveBeamForceFieldAndMass

- BeamAdapter_test/BeamInterpolation_test.cpp
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.cpp
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- Clean header includes
- update all typedef by using and remove unused one
- Update mat6x6 init in code to avoid creation followed by copy.
> [Component] Clean header includes and typedef in AdaptiveBeamForceFieldAndMass

- src/BeamAdapter/component/engine/WireRestShape.h
It is inheriting from DataEngine for no reason as the `update ` method is not used.
> [WireRestShape] Update component to inherite directly from BaseObject insteaf of DataEngine 

- src/BeamAdapter/gpu/cuda/CudaInstantiations.cpp
BeamInterpolation and WireBeamInterpolation could not be compiled due to missing float instantiation of MechanicalObject
> Fix compilation of CUDA types and add float based components

- src/BeamAdapter/component/engine/WireRestShape.h
- src/BeamAdapter/component/engine/WireRestShape.inl
The pointer to the Edge2QuatTopologyMapping mapping is not necessary to manually propagate the topological changes.
The propagation will be done automatically through topology changes pipeline.
> [WireRestShape] Remove unnecessary use of Edge2QuatTopologyMapping

- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
- src/BeamAdapter/component/engine/WireRestShape.h
Depends on PR #60 
clean (and simplify?) the method
> [InterventionalRadiologyController] Rewrite method interventionalRadiologyComputeSampling

- BeamAdapterConfig.cmake.in
- CMakeLists.txt
- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
Actually nothing was using OpenGL in BeamAdapter, only remnant headers from sofa.gl was keeping the hard dependency in the CMake files.
> Remove dependency on Sofa.GL

- src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.h
Compilation failed due to https://github.com/sofa-framework/BeamAdapter/pull/75
> Remove useless Sofa.GL include

- src/BeamAdapter/component/mapping/BeamLengthMapping.inl
There is a typo between `stepBegin` and `stepEnd`:
`AdvancedTimer::stepBegin("AdaptiveBeamMappingConstrainApplyJT");`
`AdvancedTimer::stepEnd("AdaptiveBeamMappingConstraintApplyJT");`
It has been fixed by using `ScopedAdvancedTimer`.
Note that I did not check the compilation because this file is not compiled (no reference in CMakeLists.txt)
> Fix timers by using ScopedAdvancedTimer

- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
- If no instrument is given as input, the init method was searching for a single instrument using GetContext. 
```
WBeamInterpolation * wbinterpol= context->get< WBeamInterpolation >(BaseContext::Local);
m_instrumentsList.push_back(wbinterpol);
```
The pointer was not tested so if no instrument were present in the scene, the IRCtrl was initialised with a null pointer. 
Change this method to directly fill the vector with all corresponding component found.
- Add a warning at init if the number of dof inside the current mechanicalObject is really low compare to the number of beam that can be deployed in the scene. this doesn't really fix #70 but at least warn user.
> [InterventionalRadiologyController] Improve init checks to avoid potential crashes

- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.inl
Quick change in RotateFrameForAlignX, the input vector should be already normalized.
This is to avoid multiple norm on the same vector as the method is usually called several time on the same vec in middle of other calculus:
https://github.com/epernod/BeamAdapter/blob/5f96973736a4a597cc7faddd76cc2ae6d876d0cf/src/BeamAdapter/component/BeamInterpolation.inl#L1253-L1254
> [BeamInterpolation] Update method rotateFrame to take a normalized vector

- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
- change some variable names to more explicit one (I hope)
- add some comments
- add and improve some checks
- Fix totalLengthIsChanging to not increase curve abscisses with threshold value as it messes everything. Fix #74 in most of the cases. Error message still appear sometime when going backward but doesn't crash anymore.
> [InterventionalRadiologyController] Clean method applyInterventionalRadiologyController

- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.h
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
Using SPtr.
Not only because the created AdaptiveBeamMapping were never deleted, but also there are storing a BeamInterpolation::SPtr. Thus, these BeamInterpolation objects were never deleted as well (as the ref count is not 0, kept by the mapping)
`3instruments_collis.scn -g batch -n 5000`
Before: `SUMMARY: AddressSanitizer: 612711 byte(s) leaked in 4084 allocation(s).`
After:  `SUMMARY: AddressSanitizer: 1482 byte(s) leaked in 14 allocation(s)`
(using https://github.com/sofa-framework/sofa/pull/3671 for the SOFA branch)
> [MultiAdaptiveBeamMapping] Fix memory leak

- src/BeamAdapter/component/BeamInterpolation.inl
See https://github.com/sofa-framework/sofa/pull/3741
> Replace deprecated constructor of OptionsGroup

- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
This PR addresses issue #87.
As explained in the issue, the new implementation doesn't automatically include in the sampling the key points of the instruments. Specifically, these key points are ignored if the instrument is deployed, but is not visible (i.e. if another instrument with a wider diameter is deployed further).
The implementation suggested here always adds the key points in the list of new curvilinear abscissas, and actually does a sampling on the visible instruments. This should be the same as the original behaviour
NB: I am not sure if the first key point of the interval is also taken into account in the sampling loop, or not. This shouldn't have any influence on the outcome, as the new curvilinear abscissas are sorted afterwards (with duplicated nodes removed), but if the …
> [InterventionalRadiologyController] Revert sampling change of behaviour

- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.h
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.h
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
- lots of cleanups here and there (ref, etc)
More importantly, add an optional feature: parallelize computations of apply and applyJ, using built-in parallel loop of STL.
On my bench scene (3instru_collis) it leads to a not-so-negligible gain of 5~10% gain of fps.
By default the option is false, in case of. (I cannot prove it wont lead to nonpredictable side-effects)
> [Mapping] Clean and optimize AdaptiveBeamMapping

- .github/workflows/ci.yml
- CMakeLists.txt
\+ fix for fetching regression for a branch other than master
> Workaround: Avoid error when SofaCUDA is found but CUDA is not

- src/BeamAdapter/component/WireBeamInterpolation.h
This was using an old compatibility layer to redirect `m_componentstate` to `d_componentstate`
> Use d_componentState

- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
Add a second method computeTransform with node indices as parameters to avoid multiple call of GetNodeIndices when they are already known
> [BeamInterpolation] Add method computeTransform with node indices as parameters

- src/BeamAdapter/component/controller/InterventionalRadiologyController.h
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Only cleaning/renaming to clarify the code. No behavior change.
- Rename method: `interventionalRadiologyComputeSampling `into `computeInstrumentsCurvAbs`
- spit method `sortCurvAbs ` into 2 methods:
- a first method `sortCurvAbs `which only sort curvAbs 
- a second method `fillInstrumentCurvAbsTable` which compute the id_instrument_table based on the curvAbs 
- Update some code comments in the main loop
Update methods doc and change the parameters methods to pass only the needed data
> [InterventionalRadiologyController] Split and rename methods sortCurvAbs and interventionalRadiologyComputeSampling for more clarity

- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.h
- src/BeamAdapter/component/WireBeamInterpolation.inl
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Remove all code related to drop / brokenIn2 tool. This was use to simulate the drop of a part of the catheter during a procedure. 
This code is not really working anymore and should be re-implemented, if needed, using for example engine or dedicated component instead of changing directly the structure of the beam in the RestShape / interpolation components.
> Remove code linked to brokenIn2

- BeamAdapter_test/component/mapping/BeamProjectionDifferenceMultiMappingTest.cpp
- CMakeLists.txt
- examples/python3/component/BeamProjectionDifferenceMultiMapping.py
- src/BeamAdapter/component/mapping/BeamProjectionDifferenceMultiMapping.cpp
- src/BeamAdapter/component/mapping/BeamProjectionDifferenceMultiMapping.h
- src/BeamAdapter/component/mapping/BeamProjectionDifferenceMultiMapping.inl
This PR adds a new component with an example and test.
**BeamProjectionDifferenceMultiMapping** : This mapping takes some points and a beam as inputs, and outputs the difference between the points and their projection on the beam. The output difference is expressed in the local frame (wrt the beam), allowing the set up of constraints such as a fixing constraint (ex: attach a beam to another model) and sliding constraint (ex: constrain an object to slide on a beam). 
**Example of usage** :  
(you can also try the example _examples/python3/component/BeamProjectionDifferenceMultiMapping.py_)
```python
sliding = particle.addChild('SlidingConstraint')
beam.addChild(sliding)
sliding.addObject('MechanicalObject', template='Rigid3', position=[0, 0, 0, 0, 0, 0, 0]) …
```
> [mapping] new component (BeamProjectionDifferenceMultiMapping)

- BeamAdapter_test/component/model/WireRestShape_test.cpp
- src/BeamAdapter/component/engine/WireRestShape.h
- src/BeamAdapter/component/engine/WireRestShape.inl
> [WireRestShape] Clean code related to brokenIn2 and EdgeSetTopologyModifier

- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
Implements  buildMassMatrix() and buildStiffnessMatrix() for AdaptiveBeamForceFieldAndMass.
> [forcefield] updates AdaptiveBeamForceFieldAndMass with the new matrix assembly API 

- src/BeamAdapter/component/controller/BeamAdapterActionController.inl
- src/BeamAdapter/component/controller/InterventionalRadiologyController.h
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Update `BeamAdapterActionController ` behavior:
**Before:** pressing for example key up was moving the tool forward until another action was ordered.
**Now:**: pressing a key perform only one action for the current timestep. 
This create bigger Actions and keytimes vectors but allow a smoother description and can be replay without any problem of timestep precision. 
Add mechanism in `InterventionalRadiologyController `  using bool `m_useBeamActions ` to know that is is now controlled by a 
`BeamAdapterActionController `. At this point, events are skipped in `InterventionalRadiologyController ` and everything is handled in the `BeamAdapterActionController `.
> [BeamAdapterActionController] Update Actions reading/writting and IRCtrl control

- examples/RegressionStateScenes.regression-tests
This PR is based on [PR #56](https://github.com/sofa-framework/Regression/pull/56) of Regression. 
This PR fixes the problem of running regression tests in plugins when their references are inside of the plugin and not Regression (e.g. BeamAdapter)
The idea is to have a stand alone `*.regression.tests` file that also includes the relative path of the reference folder. This is meant to be placed at the top of the reference file in a relative manne. This allows two things : 
1. Having a stand alone file ease the process of finding the reference folder for any new comer
2. Having a stand alone file ease the process of automatizing the retrieval of new regression test along with their reference folder without the need of modifying anything in the CI script.
> Add relative path to references files into regression-tests files

- doc/Doxyfile
- doc/README.md
Try to fix the links in the [doxygen doc](https://sofa-framework.github.io/BeamAdapter/index.html) in the documentation section
> Fix doc links using absolute path

- examples/python3/Cochlear-Implant-Insertion/Scene_Cochlea.py
- examples/python3/SingleBeam.py
- examples/python3/SingleBeamDeployment.py
- examples/python3/SingleBeamDeploymentCollision.py
Fix the basic examples scenes using same parameters as the xml versions. (also clean warnings)
Also fix the [Scene_Cochlea.py](https://github.com/sofa-framework/BeamAdapter/compare/master...epernod:inf_python_scene?expand=1#diff-62304f9e52c9d1607150a46a855012082b455aca495d7bb211c277a19b521e75)
Not sure if the behavior is correct, this is a screenshot of what I get:
fix #122
> [scenes] Fix python scenes using the new Section Material components

- BeamAdapter_test/component/mapping/BeamLengthMappingTest.cpp
The test is still failing but not because of a required plugin
> Fix minor things in a failing test

- extensions/CUDA/src/BeamAdapter/CUDA/init.cpp
Based on https://github.com/sofa-framework/BeamAdapter/pull/132 and requires https://github.com/sofa-framework/sofa/pull/4453. Only the last commit is important.
> Initialize SofaCUDA

- src/BeamAdapter/component/BaseBeamInterpolation.h
- src/BeamAdapter/component/BaseBeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.h
- src/BeamAdapter/component/WireBeamInterpolation.inl
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.h
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
To be able to use BaseBeamInporlation class in BeamMapping, move one remaining method from wireBeamInterpolation into BaseBeamInterpolation
This should fix scenes crashing on the SOFA dashboard
> [src] Use BaseBeamInterpolation in BeamMapping

- src/BeamAdapter/component/engine/WireRestShape.inl
- src/BeamAdapter/utils/BeamSection.h
If the x_curv is not found, no return (const ref) was done
> WireRestShape: getBeamSection() must return a const ref in any case

- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
In the case of visual mapping:
``` 
<Node name='VisuGuideCatheter'>
<MechanicalObject name='dof_visual_GC' />
<QuadSetTopologyContainer  name='ContainerGC' />
<QuadSetTopologyModifier />
<QuadSetGeometryAlgorithms template='Vec3d' />
<Edge2QuadTopologicalMapping nbPointsOnEachCircle='10' radius='2.06' input='@../../GuideCatheter/GC_mesh' output='@ContainerGC' flipNormals='true'/>
<AdaptiveBeamMapping  name='VisuMapGuideCath' useCurvAbs='1' printLog='0' interpolation='@../Interpol_GCatheter' input='@../Instrument_DOFs' output='@dof_visual_GC' isMechanical='false'  />
``` 
The Edge2QuadTopologicalMapping  is creating the tubular topology and dofs. But on the other hand, the AdaptiveBeamMapping is looking for the number of beam in the WireBeamInterpolation which is now returning 0, because …
> [src] Fix AdaptiveBeamMapping mapping at init with none deployed beam

- examples/3instruments.scn
- examples/3instruments_collis.scn
- examples/SingleBeamDeployment.scn
- examples/SingleBeamDeploymentCollision.scn
- src/BeamAdapter/component/BaseBeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.h
- src/BeamAdapter/component/WireBeamInterpolation.inl
- src/BeamAdapter/component/engine/WireRestShape.h
- src/BeamAdapter/component/engine/WireRestShape.inl
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.h
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
- src/BeamAdapter/component/model/BaseRodSectionMaterial.h
- src/BeamAdapter/component/model/BaseRodSectionMaterial.inl
Add getter for:
- `getBeamSection `
- `getInterpolationParameters`
- `getMechanicalParameters`
Depending on the modeling: 
- If `BeamInterpolation` is used. The method are overidden from `BaseBeamInterpolation` to use internal Data from `BeamInterpolation`.
- If `WireBeamInterpolation` is used: The overidden methods return the values from the `WireRestShape` which redirect to the corresponding method inside the `BaseRodSection` (depending on the current curvilinar abscissa)
**Breaking:**
- Remove the method `GetYoungModulus` by `getMechanicalParameters` as Poisson Ratio and Density of mass is also return at the same time.
- Rename several methods from xxxxParam to xxxxParameters and to xxxxParametersAtX (when depending on the curvilinear abscissa)
- Remove pointer to the `WireRestShape` …
> [src] Update RodSection, WireRestShape and All BeamInterpolation to correctly redirect the getters to the Data

- src/BeamAdapter/component/BaseBeamInterpolation.h
- src/BeamAdapter/component/BaseBeamInterpolation.inl
- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
- src/BeamAdapter/component/controller/AdaptiveBeamController.inl
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
- src/BeamAdapter/component/controller/SutureController.inl
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
- src/BeamAdapter/component/mapping/BeamLengthMapping.inl
- src/BeamAdapter/component/mapping/BeamProjectionDifferenceMultiMapping.inl
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
Previous ones were deprecated, see 
- https://github.com/sofa-framework/sofa/pull/5082
> Use constexpr VecIds

- BeamAdapter_test/component/controller/AdaptiveBeamController_test.cpp
- src/BeamAdapter/component/BeamInterpolation.cpp
- src/BeamAdapter/component/WireBeamInterpolation.cpp
- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.cpp
- src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.cpp
- src/BeamAdapter/component/controller/AdaptiveBeamController.cpp
- src/BeamAdapter/component/controller/BeamAdapterActionController.cpp
- src/BeamAdapter/component/controller/InterventionalRadiologyController.cpp
- src/BeamAdapter/component/controller/SutureController.cpp
- src/BeamAdapter/component/engine/SteerableCatheter.cpp
- src/BeamAdapter/component/engine/WireRestShape.cpp
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.cpp
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.cpp
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.cpp
- src/BeamAdapter/component/mapping/BeamLengthMapping.cpp
- src/BeamAdapter/component/mapping/BeamProjectionDifferenceMultiMapping.cpp
- src/BeamAdapter/component/mapping/BeamProjectionDifferenceMultiMapping.h
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.cpp
- src/BeamAdapter/component/model/RodMeshSection.cpp
- src/BeamAdapter/component/model/RodSpireSection.cpp
- src/BeamAdapter/component/model/RodStraightSection.cpp
- src/BeamAdapter/config.h.in
- src/BeamAdapter/initBeamAdapter.cpp
See
- [SOFA #4429](https://github.com/sofa-framework/sofa/pull/4429)
\+ :
- introducing the beamadapter namespace
- cleaning
- config.in/init conformance
A future PR should uniform/clean/make consistent the namespaces, it is a real mess
> Apply new factory registration mechanism + refresh

- BeamAdapter_test/component/model/WireRestShape_test.cpp
- src/BeamAdapter/component/BaseBeamInterpolation.h
- src/BeamAdapter/component/BaseBeamInterpolation.inl
- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.h
- src/BeamAdapter/component/WireBeamInterpolation.inl
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
- src/BeamAdapter/component/controller/SutureController.inl
- src/BeamAdapter/component/engine/WireRestShape.h
- src/BeamAdapter/component/engine/WireRestShape.inl
- src/BeamAdapter/component/model/BaseRodSectionMaterial.h
- src/BeamAdapter/component/model/RodMeshSection.h
- src/BeamAdapter/component/model/RodMeshSection.inl
- src/BeamAdapter/component/model/RodSpireSection.h
- src/BeamAdapter/component/model/RodSpireSection.inl
- src/BeamAdapter/component/model/RodStraightSection.h
- src/BeamAdapter/component/model/RodStraightSection.inl
Cleaning (a bit) the cesspool 🥴 in the interpolation/shape part
- remove all the const ref for simple types
- use more sane types for IDs/size (and use aliases for clearer intent)
- add some const for more clarity for inputs/outputs
Breaking as it changes a lot of method signatures
> [All] Clean types

- src/BeamAdapter/component/BaseBeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.h
- src/BeamAdapter/component/controller/InterventionalRadiologyController.h
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
- src/BeamAdapter/component/engine/WireRestShape.h
- src/BeamAdapter/component/engine/WireRestShape.inl
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
- src/BeamAdapter/component/model/BaseRodSectionMaterial.h
- src/BeamAdapter/component/model/BaseRodSectionMaterial.inl
In a nutshell, there is a confusion in the description of a tool, where nbEdgesCollision set the number of mechanical beams...
So in the end the number of beams will be the same as the number of collision edges. 
It is especially problematic where you want a certain part of your tool to be more "collidable" but it does not necessarily need more "beams".
There is a little compat part if a user did not specify "nbBeams", it will take the value of nbEdgesCollision (like it is now)
> [Wire Shape] Fix the confusion between the nbEdgesCollision and the number of mechanical Beams

- examples/3instruments.scn
- examples/3instruments_collis.scn
- examples/SingleBeamDeployment.scn
- examples/SingleBeamDeploymentCollision.scn
- examples/Tool_from_loader.scn
- examples/python3/SingleBeamDeployment.py
- examples/python3/SingleBeamDeploymentCollision.py
Note that there are warnings about Mass in the same node, because there are as many AdaptiveFFandMass as there are tools.
```
Warning:  [Node(InstrumentCombined)] Trying to add a BaseMass ('unnamed' [AdaptiveBeamForceFieldAndMass] 0x55e365ac6680) into the Node '/InstrumentCombined', whereas it already contains one ('CatheterForceField' [AdaptiveBeamForceFieldAndMass] 0x55e36579c810). Only one BaseMass is permitted in a Node. The previous BaseMass is replaced and the behavior is undefined.
Warning:  [Node(InstrumentCombined)] Trying to add a BaseMass ('unnamed' [AdaptiveBeamForceFieldAndMass] 0x55e36593ff40) into the Node '/InstrumentCombined', whereas it already contains one ('GuideForceField' [AdaptiveBeamForceFieldAndMass] 0x55e365ac6680). Only one BaseMass is permitted in a Node. The …
```
> [Scenes] Fix runtime warnings, and consistent behavior between python and xml

- src/BeamAdapter/component/BaseBeamInterpolation.h
- src/BeamAdapter/component/BaseBeamInterpolation.inl
- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.h
- src/BeamAdapter/component/WireBeamInterpolation.inl
Based on
- #184 
It was using raw pointer for mstate and topology, and even a pointer on the edge container (from the topology 🤪)
> [Interpolations] Remove raw ptr for mstate and topology

- CMakeLists.txt
- extensions/CUDA/CMakeLists.txt
- extensions/CUDA/src/BeamAdapter/CUDA/CudaInstantiations.cpp
- extensions/CUDA/src/BeamAdapter/CUDA/init.cpp
- src/BeamAdapter/component/engine/WireRestShape.inl
I guess nobody is using those instantiations 😅
> [BeamAdapter.CUDA] Fix for refactored SofaCUDA cmake, and overall fix compilation
