- examples/3instruments.scn
- examples/3instruments_collis.scn
- examples/AdaptiveBeamController.scn
- examples/AdaptiveBeamMapping.scn
- examples/SingleBeam.scn
- examples/SingleBeamDeployment.scn
- examples/SingleBeamDeploymentCollision.scn
- examples/python3/SingleBeamDeploymentCollision-pythonTemplatesLibrary.py
- examples/python3/SingleBeamDeploymentCollision.py
- change plugins/modules
- remove CollisionGroupManager
- rename response
> [Scenes] Update for Sofa v22.06

- .github/workflows/ci.yml
https://github.com/actions/virtual-environments/issues/5583
> Bump to macos11 for CI Worflow

- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
- src/BeamAdapter/component/engine/WireRestShape.inl
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.h
- src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.h
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
- Some restoreState were missing
- Some methods were totally empty
- Others were still using direct gl methods
> Fix draw methods in components

- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
This PR allows to set different Young's modulus and Poisson's ratio. 
I'm sorry my editor changed the line endings in `BeamInterpolation.inl`. I tried to find a solution without success...
> [BeamInterpolation] Heterogeneous properties

- src/BeamAdapter/component/controller/InterventionalRadiologyController.h
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
also update instrumentTable fill.
> [InterventionalRadiologyController] Rewrite method sortCurvAbs to use std sort + unique

- BeamAdapter_test/component/constraint/AdaptiveBeamSlidingConstraintTest.cpp
- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.cpp
- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.h
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
> Fix Compilation when SReal=float

- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
- src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
- topology was not well init as edge were added one by one manually.
```_topology->init();```  is then needed to fill the buffer **EdgeAroundVertex**
- Fix small bug in IRCtrl for loop if ```xP_noticeable_I``` is empty
> [MultiAdaptiveBeamMapping] Fix potential bug when removing baseEdge

- BeamAdapter_test/component/mapping/BeamLengthMappingTest.cpp
The test fails and I am not sure someone will take care of it. Ideally, it needs to be fixed.
> Disable BeamLengthMapping test

- BeamAdapter_test/CMakeLists.txt
Needs https://github.com/sofa-framework/sofa/pull/3955
> [Tests] Remove dependency on SceneCreator

- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
- src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
- src/BeamAdapter/component/controller/SutureController.inl
- src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
- src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
computeTransform was never called, only computeTransform2
- remove computeTransform 
- rename computeTransform2 into computeTransform
> Remove current method computeTransform and replace it by computeTransform2 in BeamInterpolation

- BeamAdapter_test/component/controller/InterventionalRadiologyController_test.cpp
- BeamAdapter_test/component/mapping/BeamLengthMappingTest.cpp
- BeamAdapter_test/component/model/WireRestShape_test.cpp
Following https://github.com/sofa-framework/sofa/pull/4495
> Fix simple api since SOFA changes

- .github/workflows/ci.yml
Added path to the lib in environment
> [ci] Fix the regression test not finding SP3

- src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.cpp
> Remove old deprecation

- examples/3instruments_collis.scn
on 3instruments_collision.scn .
Possible since 
- https://github.com/sofa-framework/sofa/pull/4362
- https://github.com/sofa-framework/sofa/pull/4388
before: `5000 iterations done in 73.286 s ( 68.2259 FPS)`
after:    `5000 iterations done in 43.573 s ( 114.75 FPS)`
~1.7x faster ✌️
> Example: apply SOFA's fix on TopologicalMapping

- examples/3instruments.scn
- examples/3instruments_collis.scn
- examples/AdaptiveBeamController.scn
- examples/AdaptiveBeamMapping.scn
- examples/SingleBeam.scn
- examples/SingleBeamDeployment.scn
- examples/SingleBeamDeploymentCollision.scn
- examples/Tool_from_loader.scn
- examples/python3/Cochlear-Implant-Insertion/Scene_Cochlea.py
- examples/python3/SingleBeamDeployment.py
- examples/python3/SingleBeamDeploymentCollision.py
> [scenes] Fix scene warnings in xml and python

- .github/workflows/ci.yml
https://github.com/sofa-framework/sofa/discussions/4979
> [ci] Sanitize the github workflow

- BeamAdapter_test/BeamInterpolation_test.cpp
to be compliant with https://github.com/sofa-framework/sofa/pull/5155
> Unit Tests: Fix loading plugins

- src/BeamAdapter/component/mapping/BeamLengthMapping.cpp
- src/BeamAdapter/component/mapping/BeamLengthMapping.h
Related to https://github.com/sofa-framework/sofa/pull/5269
> Fix compilation with FLOATING_POINT_TYPE=float

- src/BeamAdapter/component/controller/InterventionalRadiologyController.h
- src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Based on
- #175 
Useful commit https://github.com/sofa-framework/BeamAdapter/commit/856b3d8beea525a954858f63a5e91ea7b6e45df8
Remove all the useless parts about "controlled" beams. This was related to the "broken" feature which was removed long time ago (#104 )
> [InterventionalRadiologyController] Remove remnant of the "broken" feature 

- src/BeamAdapter/component/BaseBeamInterpolation.h
- src/BeamAdapter/component/BaseBeamInterpolation.inl
- src/BeamAdapter/component/BeamInterpolation.h
- src/BeamAdapter/component/BeamInterpolation.inl
- src/BeamAdapter/component/WireBeamInterpolation.inl
By removing bwdInit shenanigans and adding a forgotten super init
> [Interpolations] Fix init stage

- .github/workflows/ci.yml
This will notify the following dashboard https://sofa-framework.org:5000/dashboard
> Add 'notify dashboard' step to CI
